### ISSUE TITLE
ghc-7.10 Prelude exports Word

### ISSUE THREAD

**Issue by aavogt** [gbgar/Wordlint#2]
With ghc-7.10 (and Wordlint-0.2.0.4 from hackage) there is a compile time error like:

```
src/Wordlint/Words.hs:175:53:
    Ambiguous occurrence ‘Word’
    It could refer to either ‘Wordlint.Words.Word’,
                             defined at src/Wordlint/Words.hs:24:1
                          or ‘Prelude.Word’,
                             imported from ‘Prelude’ at src/Wordlint/Words.hs:1:8-21
                             (and originally defined in ‘ghc-prim-0.4.0.0:GHC.Types’)
```

**Comment by gbgar** [comment]
Damn, I think this will be an easy fix, but I will be busy as hell until the last week of this month. I hope this doesn't throw off your work---if it does, let me know and I will try to squeeze out time to work it out sooner. Thanks for the heads up!

**Comment by aavogt** [comment]
It's no rush. I was just interested in what suggestions word lint can give and noticed it didn't compile with the latest ghc.

You could use cpp:

```
#if __GLASGOW_HASKELL__ > 709
import Prelude hiding (Word)
#else
import Prelude
#endif

At some point, ghc was changed to treat hiding identifiers that aren't exported as a warning, instead of an error, so if you just add `import Prelude hiding Word ` it'll probably work with a warning on 7.8 and maybe 7.6 too.
```

**Comment by gbgar** [comment]
I suck. I fixed this last June/ I even bumped my version numbers and everything. Then, I never pushed to github or uploaded a new version to hackage. This makes me think I had not gotten rid of all the bugs I wanted to squish. Anyway, it compiles for me, so happy linting!
